language: cpp
compiler:
    - g++
os:
    - osx
    - linux
install:
    - export CXX=g++-5
    - cd cpp/
    - make CXX="${CXX}"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - g++-5
      - gcc-5
script:
    - cd ./../tools/
    - bash download_text8.sh
