language: cpp
compiler:
    - g++
os:
    - linux
before_install:
    - wget http://bitbucket.org/eigen/eigen/get/3.2.8.tar.gz
    - tar xzvf 3.2.8.tar.gz
install:
    - export CXX=g++-5
    - cd cpp/
    - make CXX="${CXX}" INCLUDES=-I"./../eigen-eigen-07105f7124f9/"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - g++-5
      - gcc-5
script:
    - bash ./../tools/download_text8.sh
    - gzip -d text8.gz
    - time ./kadingir_oscca --corpus text8 --output output_text8.txt --vocab 1000 --dim 40 --window 2
