language: cpp
compiler:
    - g++
os:
    - osx
    - linux
before_install:
    - wget http://bitbucket.org/eigen/eigen/get/3.2.8.tar.gz
    - tar xzvf 3.2.8.tar.gz
install:
    - export CXX=g++-5
    - cd cpp/
    - make CXX="${CXX}" INCLUDES="./../eigen-eigen-07105f7124f9/"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - g++-5
      - gcc-5
script:
    - cd ./../tools/
    - bash download_text8.sh
